name: PR checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'mix.lock'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - { elixir: '1.14.x', otp: '24.x' }
          - { elixir: '1.14.x', otp: '25.x' }
          - { elixir: '1.15.x', otp: '25.x' }
          - { elixir: '1.15.x', otp: '26.x' }

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
        with:
          otp-version: ${{ matrix.version.otp }}
          elixir-version: ${{ matrix.version.elixir }}

      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix credo
      - run: mix test
